### ISSUE TITLE
Qin 1s+ 玩机研究 | MlgmXyysd 的猫窝

### ISSUE THREAD

**Issue by MlgmXyysd** [MlgmXyysd/Comment-Issues#1]
http://mlgmxyysd.meowcat.org/2019/09/14/qin-1sp-research/

**Comment by IceFex-GH** [comment]
是大佬…我只进行到更改包名装个应用跳转activity打开adb调试就推进不下去了

**Comment by GHNNS** [comment]
异曲同工，有趣，这里有一篇8月14日破解1s+的。
https://www.myworldbooks.cn/archives/683

**Comment by Hans-Deng** [comment]
> 异曲同工，一站式，这里有一篇8月14日破解1s+的。
> https://www.myworldbooks.cn/archives/683

无法访问了

**Comment by MlgmXyysd** [comment]
* Migrated to [https://www.neko.ink/2019/09/14/qin-1sp-research/](https://www.neko.ink/2019/09/14/qin-1sp-research/)
