### ISSUE TITLE
浅谈 Xposed 新概念 [模块作用域] | MlgmXyysd 的猫窝

### ISSUE THREAD

**Issue by MlgmXyysd** [MlgmXyysd/Comment-Issues#2]
http://mlgmxyysd.meowcat.org/2019/12/28/xposed-modules-activation-scope/

**Comment by Howard20181** [comment]
来看看（｡ò ∀ ó｡）

**Comment by MlgmXyysd** [comment]
* Migrated to [https://www.neko.ink/2019/12/28/xposed-modules-activation-scope/](https://www.neko.ink/2019/12/28/xposed-modules-activation-scope/)
