### ISSUE TITLE
树莓派使用官方 64 位 Raspbian 系统 | MlgmXyysd 的猫窝

### ISSUE THREAD

**Issue by MlgmXyysd** [MlgmXyysd/Comment-Issues#7]
http://mlgmxyysd.meowcat.org/2020/03/09/raspberry-pi-64-bit/

**Comment by karuboniru** [comment]
想要优雅的用树莓派还可以考虑吧[这个项目](https://rpi4-uefi.dev/), 配合这个版本的UEFI和新版本内核理论上能使用所有(支持aarch64的)发行版

**Comment by MlgmXyysd** [comment]
* Migrated to [https://www.neko.ink/2020/03/09/raspberry-pi-64-bit/](https://www.neko.ink/2020/03/09/raspberry-pi-64-bit/)
